### ISSUE TITLE
Add RSS feed URL

### ISSUE THREAD

**Issue by drmohundro** [azurecasts/azurecasts.com#1]
I used to follow the RailsCast RSS feed so that I could be updated when new videos were posted, which made me interested in seeing an RSS feed for AzureCasts, too... _and_ `jekyll-feed` is already set up, so `/feed.xml` works.

I think the only thing missing would be something like the snippet below for automatic feed discovery:

```<link rel="alternate" type="application/rss+xml" title="AzureCasts.com" href="https://azurecasts.com/feed.xml">```

I'm happy to submit a PR for this as well.

**Comment by robconery** [comment]
Ah great idea! Added!
